# Generated by Django 5.0.1 on 2024-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_grupo_produto_email_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='grupo',
            field=models.CharField(max_length=255),
        ),
    ]
